### ISSUE TITLE
Collapsed sidebar display issues

### ISSUE THREAD

**Issue by bwhaley** [CloudPouch/CloudPouch.dev#11]
When the sidebar is collapsed and you have many AWS profiles defined in `~/.aws/config`, the sidebar is not very helpful. See screenshot.

Also, it's confusing that the hamburger menu looks odd when the arrow at the bottom of the profile selector is pressed. E.g. if the hamburger menu itself is clicked to hide the sidebar, it looks normal. But if you use the arrow to auto hide/show the profiles on mouse over, the hamburger menu becomes inaccessible.

<img width="251" alt="Screenshot 2022-12-23 at 17 52 27" src="https://user-images.githubusercontent.com/503816/209417401-3df17cda-c5ab-4f4f-93fa-13ff89f69040.png">

**Comment by serverlesspolska** [comment]
Hey @bwhaley, I started working on this issue.

**Comment by serverlesspolska** [comment]
This issue was fixed by [Release 1.25.2](https://github.com/CloudPouch/CloudPouch.dev/releases/tag/v1.25.2)
