### ISSUE TITLE
In Help should be section About with program version

### ISSUE THREAD

**Issue by ziutus** [CloudPouch/CloudPouch.dev#3]
I see that version number is showed on the bottom of main page but first place where I search version info is in Help -> About.

**Comment by serverlesspolska** [comment]
Hi @ziutus thanks for adding this issue. I will implement it.

For time beeing you can see the version number at the bottom of the app. 
![image](https://user-images.githubusercontent.com/22025007/145178545-6e1d51f4-f6cf-4c68-a2ce-1a703780633c.png)
