### ISSUE TITLE
AWS Organizations button doesn't work

### ISSUE THREAD

**Issue by ziutus** [CloudPouch/CloudPouch.dev#7]
AWS Organizations button doesn't work whole appliactions stops to work (hang) and it must be restarted.

**Comment by serverlesspolska** [comment]
@ziutus could you please tell on which version problem occurred.

I just tested version 1.15.1 and it works flawlessly in my AWS Organization.

**Comment by serverlesspolska** [comment]
This bug was fixed in `1.20.2`.
